<?xml version="1.0" ?>
<testsuite name="unittest.loader._FailedTest-20240612212614" tests="1" time="0.000" failures="0" errors="1">
	<testcase classname="unittest.loader._FailedTest" name="e2etests" time="0.000">
		<error type="ImportError" message="Failed to import test module: e2etests
Traceback (most recent call last):
  File &quot;/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'e2etests'
"><![CDATA[ImportError: Failed to import test module: e2etests
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'e2etests'

]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
